---
title: move-staging
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
description: FF&E specialists Move-In provide apartment packages for hotels, services
  apartments, private villas and more.
keywords: apartment packages, ff&e, apartment furniture packages, hotel ff&e, furniture
  packages, ff&e design, complete furniture package deals, home furnishings, interior
  designers, fully furnished apartments, hotels & resorts, investor, executive and
  corporate leasing, design consultation, multi-room furniture packages, interior
  styling, furniture design
typekit: ayw8ltr
analytics: UA-24242192-1
instagram: http://instagram.com/move_in_furniture
newsletter: http://eepurl.com/QwmVr
say hello link: mailto:enquiries@move-in.com.au
